### ISSUE TITLE
Graph x axis (games played) becoming cluttered 

### ISSUE THREAD

**Issue by Razza99** [gcp/leela-zero-server#10]
As we are nearing 4 million games played, would it be worth displaying in multiples of 1,000 or 1,000,000 for ease of viewing?

**Comment by roy7** [comment]
https://github.com/d3/d3-format#locale_format

I think holds the secrets!

**Comment by Razza99** [comment]
That would display the xticks as 3.2M, 3.4M, etc ?
Another way might be to have the x axis title as 'Games played (x1,000,00)', and display the xticks just as 3,2, 3.4, etc.

I'm not sure which is preferable

**Comment by Razza99** [comment]
I wonder if this is a self-solving problem... maybe Vega-lite will redo the xticks when we go over 4M games played?
