### ISSUE TITLE
what is the meaning of self-game lists?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero-server#124]
View most recent self-play games: b6337c69/176b WGo, b6337c69/143w WGo, b6337c69/491b WGo, 62b5417b/92b WGo, b6337c69/228b WGo, 62b5417b/93w WGo, b6337c69/114b WGo, 62b5417b/101w WGo, b6337c69/157w WGo, 62b5417b/110b WGo

I guess hash/total moves_winnercolor

**Comment by l1t1** [comment]
confirmed.
I also saw them at http://zero.sjeng.org/self-plays (https://github.com/gcp/leela-zero/issues/1416), it is a nice view

**Comment by Mardak** [comment]
Yes. We're shortening the hash to be 4 long instead of the usual 8, so it doesn't take up as much space. Also only linking to WGo.

**Comment by l1t1** [comment]
it is quite clean now
View most recent self-play games: b633/113w, b633/107w, b633/112b, b633/93w, b633/667b, b633/503b, b633/401w, b633/544b, 62b5/93w, 62b5/173w
