### ISSUE TITLE
your most recent self-play games shows wrong order

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero-server#128]
View your most recent self-play games: 9056/183w, 9056/116b, 62b5/164b, 62b5/93w, b633/153w, b633/228b, 62b5/95w, b633/178b

but I print the log on my computer, the recent finished games don't include 62b5 game or b633 game

-----

C:\Users\lutao\Downloads>type zeros.txt | find "Game data"
Game data 5145759e7f173f075842175a248927a68f8f170ae00237212e064ccae9a93478 stored in 

database
Game data 42f651e19f0a01e23e1ff831b28d3abd5321dac5d57a7badeb086152f28b117c stored in 

database
Game data 4ad4630661a8e27e20420cbce408355d937be6a9f38c23134bcf0d27b6d780b5 stored in 

database
Game data 4bf59ecd63e4a5e55fa40897a3d74c19f1a7ad3befb752fbee3d29a62ff50d9e stored in 

database
Game data 0617474d6fdacb30c90f4a591796fd147f9b6c4870f4a02cae678b9dedb7e2af stored in 

database
Game data b407d5b4c6e9c46897e1f94d9fae8c62efb0cd1c55163596c538b7a1d75668ae stored in 

database
Game data ff70c18312e1af59ba0a7033e254fb71d3b6e8798759d72794cafdab0a3f59e5 stored in 

database
Game data ef1af8e951773b8418fc4c3e89a2b6fce30c128fb63cd4600a012ce40c1f54f9 stored in 

database
Game data e5862d3ea4a5943553516d5e76afa783fa880e816c4caf20c279a66cc39b7458 stored in 

database
Game data 0775ff22bbb75facae53a69b2932c94fa47067ceb87f3b66e79f02beac7fb447 stored in 

database
Game data 8cb4ce4c8660bcc96b53a67d073314b44e0ae767258b9e96b053988f8873704a stored in 

database
Game data 89b8ba763667b9245d00acd04153ba530fe1d972de1fa3a1ad9b69874f00b66b stored in 

database
Game data a6f0058c760c6e4923e3b337456c2faf910d4fa1267394820fe7bc6785f7b863 stored in 

database
Game data 12fe694b4e555d6869e5922b4a191dcf52f74954a06b558c4044fc2de793e1df stored in 

database
Game data 650aff69bc2dfbb3f90061dbf264c253455953e12846dfc5e31f795c89259aee stored in 

database
Game data 73dc6c823d9f10a99cd8021852cf7390fe9aa1bed3f0d96bf289d3398f9c8b9d stored in 

database
Game data cdf405a6de43c14544da079208453ce23534c65c502aabe5c917a444d671821a stored in 

database
Game data f83a0f31905250879566420313c1799537135ac89885cab2f8755d4be283bab5 stored in 

database
Game data e0aaa016c605e79209ead1f67c2080599f63ce985172974b9da448940c0dca37 stored in 

database
Game data 62af51005729cb7381ff84008e4886973210f07e60947afeab3a12bb2c8f7c78 stored in 

database
Game data 192399a9b5a9b755c0826930c6edd822db046b3580235227e2729016d8e6c69a stored in 

database
Game data 91b806466c57e4d441d8320c4145831bc28bec5f71548dd66bfaa51ec8c4e87b stored in 

database

C:\Users\lutao\Downloads>type zeros.txt | find "Score:"
Score: B+Resign
Score: W+Resign
Score: B+Resign
Score: W+Resign
Score: B+Resign
Score: B+Resign
Score: W+Resign
Score: W+Resign
Score: W+Resign
Score: W+Resign
Score: B+Resign
Score: W+Resign
Score: B+Resign
Score: B+Resign
Score: B+Resign
Score: B+Resign
Score: B+Resign
Score: W+Resign
Score: W+Resign
Score: B+Resign
Score: B+Resign
Score: W+Resign

C:\Users\lutao\Downloads>type zeros.txt | find "resign)"
(W L12) 175 (B L11) 176 (W L14) 177 (B M15) 178 (W resign) Game has ended.
13) 92 (W A17) 93 (B A10) 94 (W C16) 95 (B resign) Game has ended.
W L8) 115 (B J9) 116 (W resign) Game has ended.
46 (W M5) 147 (B L4) 148 (W B18) 149 (B resign) Game has ended.
 resign) Game has ended.
) 92 (W K12) 93 (B J10) 94 (W J5) 95 (B L12) 96 (W resign) Game has ended.
 A18) 197 (B resign) Game has ended.
6 (W H11) 147 (B G14) 148 (W G10) 149 (B E15) 150 (W M13) 151 (B N14) 152 (W Q18) 153 (B 

resign) Game has ended.
 B5) 92 (W F5) 93 (B resign) Game has ended.
(B resign) Game has ended.
) 157 (B G4) 158 (W F3) 159 (B Q14) 160 (W S13) 161 (B H13) 162 (W E3) 163 (B G6) 164 (W 

resign) Game has ended.
W G11) 95 (B A12) 96 (W H10) 97 (B resign) Game has ended.
) 113 (B A13) 114 (W K8) 115 (B A15) 116 (W resign) Game has ended.
 P9) 146 (W resign) Game has ended.
6 (W J7) 127 (B K7) 128 (W resign) Game has ended.
 M11) 137 (B M12) 138 (W K13) 139 (B L14) 140 (W K14) 141 (B M13) 142 (W resign) Game has 

ended.
) 197 (B C19) 198 (W H16) 199 (B Q5) 200 (W P5) 201 (B T3) 202 (W H11) 203 (B E12) 204 (W 

D11) 205 (B resign) Game has e

) 115 (B L10) 116 (W G16) 117 (B H2) 118 (W G17) 119 (B resign) Game has ended.
17) 137 (B E8) 138 (W resign) Game has ended.
) 177 (B T15) 178 (W H6) 179 (B F13) 180 (W E13) 181 (B F12) 182 (W F11) 183 (B resign) 

Game has ended.

C:\Users\lutao\Downloads>type zeros.txt | find "net: "
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 90560d926216c9842add40913a023fd59fde761a64014c48d8246648ddd272a3.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.

**Comment by l1t1** [comment]
![2018-05-15_110916](https://user-images.githubusercontent.com/23301704/40034836-5cb5ec42-5831-11e8-9a39-cee16deb6340.png)

[zeros.zip](https://github.com/gcp/leela-zero-server/files/2003341/zeros.zip)

**Comment by roy7** [comment]
Perhaps the sort order is reversed.

**Comment by l1t1** [comment]
how does the page judge my recent games?

**Comment by Mardak** [comment]
The list should be showing most recently submitted first. Maybe the IP address is not consistently the same on submit?

You said you saw: "9056/183w, 9056/116b, 62b5/164b, 62b5/93w, b633/153w, b633/228b, 62b5/95w, b633/178b"

These below are from your logs, and they mostly match up with the recent list and in the expected order:
```
 (W L12) 175 (B L11) 176 (W L14) 177 (B M15) 178 (W resign) Game has ended.
 13) 92 (W A17) 93 (B A10) 94 (W C16) 95 (B resign) Game has ended.
?? missing ?? 228 (W resign)
 6 (W H11) 147 (B G14) 148 (W G10) 149 (B E15) 150 (W M13) 151 (B N14) 152 (W Q18) 153 (B resign) Game has ended.
 B5) 92 (W F5) 93 (B resign) Game has ended.
 ) 157 (B G4) 158 (W F3) 159 (B Q14) 160 (W S13) 161 (B H13) 162 (W E3) 163 (B G6) 164 (W resign) Game has ended.
 ) 113 (B A13) 114 (W K8) 115 (B A15) 116 (W resign) Game has ended.
 ) 177 (B T15) 178 (W H6) 179 (B F13) 180 (W E13) 181 (B F12) 182 (W F11) 183 (B resign)
```

Your log had more submitted entries than what I picked out above, so that's why I was asking if the IP address could appears different each submission. Similarly, "b633/228b" is missing, but maybe someone else is running autogtp and happened to appear as the same IP address?

**Comment by l1t1** [comment]
I use a proxy server to vist internet, so my ip won't change today
now，my page
View your most recent self-play games: 62b5/92b, 9056/183w, 9056/116b, 62b5/164b, 62b5/93w, b633/153w, b633/228b, 62b5/95w, b633/178b
but  today, all games my computer run are of 62b5 & 9056.
[zero2.zip](https://github.com/gcp/leela-zero-server/files/2004060/zero2.zip)

**Comment by l1t1** [comment]
my recent 12 games stored in database are
5145759e7f173f075842175a248927a68f8f170ae00237212e064ccae9a93478
42f651e19f0a01e23e1ff831b28d3abd5321dac5d57a7badeb086152f28b117c
4ad4630661a8e27e20420cbce408355d937be6a9f38c23134bcf0d27b6d780b5
4bf59ecd63e4a5e55fa40897a3d74c19f1a7ad3befb752fbee3d29a62ff50d9e
0617474d6fdacb30c90f4a591796fd147f9b6c4870f4a02cae678b9dedb7e2af
b407d5b4c6e9c46897e1f94d9fae8c62efb0cd1c55163596c538b7a1d75668ae
ff70c18312e1af59ba0a7033e254fb71d3b6e8798759d72794cafdab0a3f59e5
ef1af8e951773b8418fc4c3e89a2b6fce30c128fb63cd4600a012ce40c1f54f9
e5862d3ea4a5943553516d5e76afa783fa880e816c4caf20c279a66cc39b7458
0775ff22bbb75facae53a69b2932c94fa47067ceb87f3b66e79f02beac7fb447
8cb4ce4c8660bcc96b53a67d073314b44e0ae767258b9e96b053988f8873704a
89b8ba763667b9245d00acd04153ba530fe1d972de1fa3a1ad9b69874f00b66b
a6f0058c760c6e4923e3b337456c2faf910d4fa1267394820fe7bc6785f7b863
12fe694b4e555d6869e5922b4a191dcf52f74954a06b558c4044fc2de793e1df
650aff69bc2dfbb3f90061dbf264c253455953e12846dfc5e31f795c89259aee
73dc6c823d9f10a99cd8021852cf7390fe9aa1bed3f0d96bf289d3398f9c8b9d
cdf405a6de43c14544da079208453ce23534c65c502aabe5c917a444d671821a
f83a0f31905250879566420313c1799537135ac89885cab2f8755d4be283bab5
e0aaa016c605e79209ead1f67c2080599f63ce985172974b9da448940c0dca37
62af51005729cb7381ff84008e4886973210f07e60947afeab3a12bb2c8f7c78
192399a9b5a9b755c0826930c6edd822db046b3580235227e2729016d8e6c69a
91b806466c57e4d441d8320c4145831bc28bec5f71548dd66bfaa51ec8c4e87b
dde69ac20edeae0610507a756a182937bd897d4dba357f98d44263cdb1914f08
f05e9abab0a4a967b109da0f342b6cc940319fd33c1c8ba19e81d2194eed8c71
c49f8b59d057d8717b63918bd22a543a961eb4d5f2a25408473fa7b3eaf591f0
f017d62e01ff6648cb74f528a45b61e7074c1c343013b809633f7114a654442c
d0116f96833e372101656f8ea4c470460551d7d004993d1a23330725bab8688a

**Comment by l1t1** [comment]
pages shows

[url=http://zero.sjeng.org/view/dde69ac20edeae0610507a756a182937bd897d4dba357f98d44263cdb1914f08?viewer=wgo]62b5/92b[/url], [url=http://zero.sjeng.org/view/91b806466c57e4d441d8320c4145831bc28bec5f71548dd66bfaa51ec8c4e87b?viewer=wgo]9056/183w[/url], [url=http://zero.sjeng.org/view/a6f0058c760c6e4923e3b337456c2faf910d4fa1267394820fe7bc6785f7b863?viewer=wgo]9056/116b[/url], [url=http://zero.sjeng.org/view/8cb4ce4c8660bcc96b53a67d073314b44e0ae767258b9e96b053988f8873704a?viewer=wgo]62b5/164b[/url], [url=http://zero.sjeng.org/view/e5862d3ea4a5943553516d5e76afa783fa880e816c4caf20c279a66cc39b7458?viewer=wgo]62b5/93w[/url], [url=http://zero.sjeng.org/view/ef1af8e951773b8418fc4c3e89a2b6fce30c128fb63cd4600a012ce40c1f54f9?viewer=wgo]b633/153w[/url], [url=http://zero.sjeng.org/view/0617474d6fdacb30c90f4a591796fd147f9b6c4870f4a02cae678b9dedb7e2af?viewer=wgo]b633/228b[/url], [url=http://zero.sjeng.org/view/42f651e19f0a01e23e1ff831b28d3abd5321dac5d57a7badeb086152f28b117c?viewer=wgo]62b5/95w[/url], [url=http://zero.sjeng.org/view/5145759e7f173f075842175a248927a68f8f170ae00237212e064ccae9a93478?viewer=wgo]b633/178b[/url]

**Comment by l1t1** [comment]
and i refresh the page
View your most recent self-play games: 9056/138b, 9056/142b, 9056/146b, 9056/145w
whose links are

[url=http://zero.sjeng.org/view/192399a9b5a9b755c0826930c6edd822db046b3580235227e2729016d8e6c69a?viewer=wgo]9056/138b[/url], [url=http://zero.sjeng.org/view/cdf405a6de43c14544da079208453ce23534c65c502aabe5c917a444d671821a?viewer=wgo]9056/142b[/url], [url=http://zero.sjeng.org/view/12fe694b4e555d6869e5922b4a191dcf52f74954a06b558c4044fc2de793e1df?viewer=wgo]9056/146b[/url], [url=http://zero.sjeng.org/view/0775ff22bbb75facae53a69b2932c94fa47067ceb87f3b66e79f02beac7fb447?viewer=wgo]9056/145w[/url]

**Comment by roy7** [comment]
It works based on IP address so if others use the same proxy you do it will mix them all together. Or if your IP address ever changes then those prior games will disappear. We don't have any other way to detect "your" games.

**Comment by l1t1** [comment]
very old item seems disapear now, but some recent games don't show( with number marked is shown)
View your most recent self-play games: 62b5/93w, 62b5/100b, 9056/507b, 9056/138b, 9056/142b, 9056/146b, 9056/145w

could you check the ip of games not shown, are they diifferent with that shown?

----

7 Game data ef1af8e951773b8418fc4c3e89a2b6fce30c128fb63cd4600a012ce40c1f54f9
Game data e5862d3ea4a5943553516d5e76afa783fa880e816c4caf20c279a66cc39b7458
Game data 0775ff22bbb75facae53a69b2932c94fa47067ceb87f3b66e79f02beac7fb447
Game data 8cb4ce4c8660bcc96b53a67d073314b44e0ae767258b9e96b053988f8873704a
Game data 89b8ba763667b9245d00acd04153ba530fe1d972de1fa3a1ad9b69874f00b66b
Game data a6f0058c760c6e4923e3b337456c2faf910d4fa1267394820fe7bc6785f7b863
6 Game data 12fe694b4e555d6869e5922b4a191dcf52f74954a06b558c4044fc2de793e1df
Game data 650aff69bc2dfbb3f90061dbf264c253455953e12846dfc5e31f795c89259aee
Game data 73dc6c823d9f10a99cd8021852cf7390fe9aa1bed3f0d96bf289d3398f9c8b9d
5 Game data cdf405a6de43c14544da079208453ce23534c65c502aabe5c917a444d671821a
Game data f83a0f31905250879566420313c1799537135ac89885cab2f8755d4be283bab5
Game data e0aaa016c605e79209ead1f67c2080599f63ce985172974b9da448940c0dca37
Game data 62af51005729cb7381ff84008e4886973210f07e60947afeab3a12bb2c8f7c78
4 Game data 192399a9b5a9b755c0826930c6edd822db046b3580235227e2729016d8e6c69a
Game data 91b806466c57e4d441d8320c4145831bc28bec5f71548dd66bfaa51ec8c4e87b
Game data dde69ac20edeae0610507a756a182937bd897d4dba357f98d44263cdb1914f08
Game data f05e9abab0a4a967b109da0f342b6cc940319fd33c1c8ba19e81d2194eed8c71
Game data c49f8b59d057d8717b63918bd22a543a961eb4d5f2a25408473fa7b3eaf591f0
Game data f017d62e01ff6648cb74f528a45b61e7074c1c343013b809633f7114a654442c
Game data d0116f96833e372101656f8ea4c470460551d7d004993d1a23330725bab8688a
Game data e437673e3305d41ea0bc21dcddcf1140ed9d854f28c6781763b3a9ac0f9d2df3
Game data be9532afa999a0955862776ae25631c764699729c3abc4ead9907f73b5f2e4fa
3 Game data 62a9e8caf9ad4a55a88e602877e5b682c296145015bdb10cb55dc9dcba0afdd1
2 Game data e0dc71ca8704e4031fef48f31665fbfb11390f04b1058d140ed4af0eed01fb26
1 Game data db23c6b12416adfe136c6e9791d517a8792085ad577610197bd7c674a941fa74

**Comment by l1t1** [comment]
compare  the above two lists, an insteresting thing is that each time games shown on page are very different. maybe my IP of proxy always change from time to time?

**Comment by roy7** [comment]
It's also possible the proxy has multiple IP addresses or the address is
sometimes being seen at IPv4 and other times IPv6.

**Comment by l1t1** [comment]
thanks @roy7
