### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero-server#134]
Server has a memory leak of some sort it seems. 

http://termbin.com/bwxj

I'm not sure which recent change(s) in the past few days could cause Node to balloon up to 1.4G of ram in just a few hours. No new networks were uploaded that I can see so there's no memory stats dumps in log since last restart. Should we maybe use SetInterval to dump memory stats to log every 15 minutes or something?

Here's what top looks like after a fresh restart of the node server process.

```
KiB Mem :  2048072 total,   150008 free,  1390820 used,   507244 buff/cache
KiB Swap:  2812924 total,  2622068 free,   190856 used.   475728 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17354 jroy      20   0 1254276  76580  22724 R   1.0  3.7   0:06.10 node
31051 mongodb   20   0 2250160 1.156g      0 S   1.0 59.2   2876:09 mongod
```

**Comment by roy7** [comment]
Now that I'm storing memory dumps every 10 minutes, here's a few.

10 minute interval
        rss        92.88 MB
        heapTotal  45.61 MB
        heapUsed   29.16 MB
        external   17.49 MB

10 minute interval
        rss       108.77 MB
        heapTotal  43.56 MB
        heapUsed   28.49 MB
        external   26.40 MB

10 minute interval
        rss       130.45 MB
        heapTotal  68.11 MB
        heapUsed   40.99 MB
        external   20.17 MB

**Comment by Mardak** [comment]
Locally, just plain `$ node --inspect --expose-gc server.js` and loading the main page 10 times shows 10 instances of `(function(pug /*``*/) { function template(locals) {var pug_html = "", pug_mixins ` strings that don't go away with `global.gc()` when comparing heaps just like the screenshot https://github.com/pugjs/pug/issues/2972#issuecomment-377678866

A later comment suggests using `NODE_ENV=production`: https://github.com/pugjs/pug/issues/2972#issuecomment-377924736

And running locally `$ NODE_ENV=production node --inspect --expose-gc server.js` the strings don't appear.

**Comment by Mardak** [comment]
Although looking at the v8 issue, this might only happen when DevTools is opened to inspect memory to begin with…

**Comment by roy7** [comment]
NODE_ENV=production

is now set. Do we need to do something about compiling or caching the pug views? I thought caching was automatic.

**Comment by rchs819** [comment]
700MB doesn’t look right. 
I’ll look into rss generation function again

**Comment by roy7** [comment]
Right now I think we only dump memory stats summary every 10 minutes. We could add before/after dumps every time a new network is added or every time we reset the fastclients cache or whatever if we think it might be related to either of those.

Here's the last rss grep results from the prior log up to the crash.

```
        rss       187.02 MB
        rss       173.32 MB
        rss       173.32 MB
        rss       176.59 MB
        rss       185.62 MB
        rss       182.34 MB
        rss       173.10 MB
        rss       175.58 MB
        rss       146.19 MB
        rss       172.65 MB
```

**Comment by roy7** [comment]
It isn't network file uploading. I looked over all of them and every time the memory before and after the submit network processing was about the same?

Here's a big memory usage moment for example:

```
submit network start
        rss       439.46 MB
        heapTotal 316.54 MB
        heapUsed  287.26 MB
        external   20.99 MB
35.233.66.50 (35.233.66.50) uploaded in 806s LZ game #7539282: e97e596c9a03e9211b09e818f2aecc9d15521505b463bad95b205f687cae7d5b
35.233.66.50 (35.233.66.50) got task: selfplay {"cmd":"selfplay","hash":"62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9","required_client_version":"16","minimum_autogtp_version":"16","random_seed":"68457911
56791198348","minimum_leelaz_version":"0.15","options_hash":"df715e","options":{"playouts":"0","visits":"3201","resignation_percent":"5","noise":"true","randomcnt":"999"}}
Network weights (192 x 15) c28a42a8aca2e06b007317056cb34a969217a14de68a3341408c30d723db3f3f (7599934) uploaded!
submit network ends
        rss       441.36 MB
        heapTotal 320.04 MB
        heapUsed  288.63 MB
        external   36.02 MB
```

**Comment by rchs819** [comment]
From looking at submit network log
The start and end stats have little difference. 

Could you spot big difference between start and end from the log?

**Comment by roy7** [comment]
I couldnt. Maybe whole we debug i should dump memory stats every 30 seconds instead of 10 minutes?

**Comment by roy7** [comment]
Fixed latest memory issue with https://github.com/gcp/leela-zero-server/commit/97f68e3630b913cf6e1b3aa9a45d750e7ee933df
