### ISSUE TITLE
Old autogtp doesn't understand minimum_autogtp_version

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero-server#138]
@roy7 https://github.com/gcp/leela-zero-server/commit/aa4528dc23ddb20982a0dc1ec53aa0b48717543b was a bit hasty in removing `required_client_version` as that's what old clients understand.

**Comment by Mardak** [comment]
Practically, clients are behaving the same without the change to `minimum_autogtp_version` as pre-16 autogtp clients were probably on 15/0.13. The server knows to only send ELF tasks to newer clients. The main downside for these older clients not upgrading is that their T=1 games might pick single-visit moves.

**Comment by marcocalignano** [comment]
Yes to force the update you need to send `"required_client_version": 16` to the old clients and then when they all are at 16 you can change to `minimum_autogtp_version`.
Of course you can send them both until we reach version 17 (to be sure).

**Comment by roy7** [comment]
Don't I require that already?

**Comment by roy7** [comment]
Oh right. Old clients don't understand they are outdated. I am dumb. Will fix asap when I am back online, about 30 minutes.

**Comment by roy7** [comment]
Fixed!
