### ISSUE TITLE
How to startup a server

### ISSUE THREAD

**Issue by Godady** [gcp/leela-zero-server#155]
Since I want to set up a server for my Leela-zero 13X13 training, I followed readme docs and now i can visit the server website through default 8888 port. But i cant get best-netwoek or hash weight from server, that is i can not start training. I feel i have problem with the initialization about default weights file. I cant find any place i can upload a network either 19X19 or 13X13. And when I want to upload through /submit-network. I get auth_key error. Anyway, could you please give me some clue about how two startup the server from zero! Thanks a lot!
ps: below is a log.
best_network_hash_promise begins
        rss        57.19 MB
        heapTotal  34.92 MB
        heapUsed   19.84 MB
        external   17.18 MB
Streams prepared
        rss        57.19 MB
        heapTotal  34.92 MB
        heapUsed   19.89 MB
        external   17.20 MB
0 networks.
undefined LZ games, undefined ELF games.
listening on 8080
Streams completed: b576d89a4a81c7551b6e82a317a5fc6a74887767c3088fa5fa9456a127a413ba
        rss        73.98 MB
        heapTotal  36.38 MB
        heapUsed   17.53 MB
        external   48.59 MB
Current best hash b576d89a4a81c7551b6e82a317a5fc6a74887767c3088fa5fa9456a127a413ba
::ffff:106.57.234.240 Sending index.html
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.

**Comment by roy7** [comment]
auth_key is a text file you make on your server with whatever passphrase you want in it, then you pass that to the submit-network command with "key=whatever" when uploading a network. This way noone can upload to server except people who know the password.

For a brand new server put your starting random weights file into network/ folder named "best-network.gz". :)

**Comment by Godady** [comment]
But do i still need a  hash.gz  file put in network directory. How can i generate the hash.

**Comment by roy7** [comment]
I asked on Discord. Does this help?

> It's on the readme
> Under "Supervised learning with Tensorflow"
> When you run Tensorflow training, it creates a brand new untrained weights file with the blocks and filters you set it to, and starts training it
> Just run parse.py with this command, where train.out is your prepared training data (supervised games, or Leela Zero games) training/tf/parse.py train.out
> That makes the "random" initial weight file

**Comment by roy7** [comment]
@Godady Are you all set now? If so we can close this issue.
