### ISSUE TITLE
pass / fail rules

### ISSUE THREAD

**Issue by bvandenbon** [gcp/leela-zero-server#175]
Why did this pass ?
2018-06-02 21:59 | 0cb74be2  VS  b69158ea | 215 : 185 (**53.75%**) | 400 / 400 | PASS

By contrast, why did this iteration fail ?
2018-06-01 12:542.4 weeks ago | ee8b18f7  VS  b69158ea | 216 : 185 (**53.87%**) | 401 / 400 | fail

Could somebody clarify the exact rules for a pass/fail ?
(Sorry if I overlooked it in the FAQ, I couldn't find it)

Thank you in advance

**Comment by roy7** [comment]
Once a network passes it will never un-pass, if you click on the "VS" in the match table you can see the log (with running win %) of all of the match history. The win rate must have been high enough at some point to pass but then later results that came in after passing brought the average win rate down lower.

**Comment by bvandenbon** [comment]
That's super, thanks.
That explains a lot.
