### ISSUE TITLE
the website down?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero-server#176]
http://zero.sjeng.org/match-games/5b2af76148e3e5462ada6825

Network Error (tcp_error)
--
A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems  preventing it from responding to requests. You may wish to try again at a  later time.
For assistance, contact your network support team

**Comment by l1t1** [comment]
and autogtp reports

```
Uploading game: 26607d7876a645f3aed8808b4757fbdd.sgf for network 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Operation timed out"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
6 game(s) (6 self played and 0 matches) played in 989 minutes = 9891 seconds/game, 54396 ms/move, last game took 9461 seconds.
{
    "cmd": "selfplay",
    "hash": "2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "3201"
    },
    "options_hash": "df715e",
    "random_seed": "5496721016923805304",
    "required_client_version": "16"
}

Got new job: selfplay
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
```

**Comment by roy7** [comment]
Logs show

```(node:17962) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'game_count' of undefined
    at Object.update_matches_stats_cache (/home/jroy/code/leela-zero-server/classes/dbutils.js:49:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6386)```

**Comment by roy7** [comment]
Just looking for errors in the log file, also saw this.

```
(node:13394) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_id' of undefined
    at Object.new_matches_cache (/home/jroy/code/leela-zero-server/classes/dbutils.js:62:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:13394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

But the _id error happens a lot less than the game_count error.

**Comment by roy7** [comment]
Web site itself is working fine for me and matches are coming in, so these errors may or may not be related to the actual web site offline report. I don't know.

**Comment by l1t1** [comment]
I wonder why the client can get task, even if the website down?

```
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may
wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
7 game(s) (7 self played and 0 matches) played in 1147 minutes = 9836 seconds/game, 56438 ms/move, last game took 9356 s
econds.
{
    "cmd": "selfplay",
    "hash": "2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "3201"
    },
    "options_hash": "df715e",
    "random_seed": "5496721016923805304",
    "required_client_version": "16"
}

Got new job: selfplay
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
```

**Comment by bood** [comment]
@roy7 As I understood, NodeJs/express is single threaded, i.e. only one piece of javascript code is being run at the same time. Match cache of the new page is not cleared when new match arrives, it only get modified with the new match. I'll do more investigation.

**Comment by Mardak** [comment]
As @rchs819 pointed out on slack, the actual issue reported here is most likely not caused by a race, so the changes in #177 doesn't actually fix the problem while also adding a lot of complexity.

A new match against the best network does not specify a network2:
https://github.com/gcp/leela-zero-server/blob/b49274bd8c1d7fe4b88b10c6c2de7218eded2266/server.js#L424-L425

This means there will be no `new_match` found:
https://github.com/gcp/leela-zero-server/blob/b49274bd8c1d7fe4b88b10c6c2de7218eded2266/classes/dbutils.js#L61-L62

… resulting in `(node:13394) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_id' of undefined`

That's because the `$lookup` "join" for network2 requires it to not be null (and match an actual network):
https://github.com/gcp/leela-zero-server/blob/b49274bd8c1d7fe4b88b10c6c2de7218eded2266/classes/dbutils.js#L14

Because the match doesn't get added to the cache, it can't update stats:
https://github.com/gcp/leela-zero-server/blob/b49274bd8c1d7fe4b88b10c6c2de7218eded2266/classes/dbutils.js#L48-L49

… resulting in `(node:17962) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'game_count' of undefined`
