### ISSUE TITLE
Missing networks

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero-server#187]
A bunch of old networks are missing. I didnt check all of them but at least LZ25, LZ5 and LZ56 are missing.

**Comment by rchs819** [comment]
IIRC @gcp moved the old networks somewhere else to save some space on the server.
I'll try if I can find the issue #

**Comment by gcp** [comment]
I'll copy these back. Probably made a mistake when backing them up.

**Comment by gcp** [comment]
This should be fixed now.

**Comment by gcp** [comment]
https://storage.sjeng.org/networks has the old ones that failed.
