### ISSUE TITLE
Only give "NEW_RELEASE" message to old clients.

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero-server#20]
Right now i'm on 0.12 and i still get this message.

> "NEW_RELEASE": "Please upgrade to leelaz 0.12 and autogtp 14"

**Comment by marcocalignano** [comment]
@roy7 autogtp v14 ask this URL  http://zero.sjeng.org/get-task/14 for jobs or http://zero.sjeng.org/get-task/0 for tuning so you can put the "NEW RELEASE" test on all the other.

**Comment by roy7** [comment]
Yeah that's why we use the version # but it didn't occur to me at the time. Oops. :)

I've turned the message off and we've forced the upgrade now.

**Comment by Dorus** [comment]
That works too. Still might be a good idea to keep a mechanism like this in the code so we can quickly use it for the next upgrade.
