### ISSUE TITLE
Required # of matches < 0

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero-server#26]
@Dorus 
[13:23]KillerDucky: roy7 where is the next match? 2995 is in the network list already
[13:24]roy7: hm
[13:25]roy7: Match is in queue vs null
[13:28]KillerDucky: also why did d996 do 521 games?
[13:28]roy7: Need -9 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
[13:28]KillerDucky: heh
[13:29]roy7: Hmm.
[13:29]roy7: Need 26 match games. Requested 27, deleted 0. Oldest 28.70m ago. Will schedule selfplay.
[13:29]roy7: Cleared match cache.
[13:29]roy7: SPRT: Early fail pop: {
[13:30]roy7: Need -9 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
[13:32]roy7: I'll have to restart server.
[13:33]roy7: Something isn't getting cleared properly I guess when match cache is cleared.

I didn't look into the one that had 521 games but if the # requested is drifting into the negatives somehow, then perhaps it's queuing more and more over time.

**Comment by Dorus** [comment]
The 521 games is probably because those matches ran slower on the larger net, so it overshot a bit more.

The negative matches make no sense, idk what caused that. Did it somehow mix match games from one matches to the other? Somehow ` games_left = max_games - w_obs - l_obs` became -34 ?

**Comment by roy7** [comment]
Happened again.

Need -16 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -16 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
XXX  uploaded match 0fb78565a116c99ba315964b9e8770a86b758422a80c07b0e557bb719b454934
Need -17 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.

I guess for a work around we need to add a check if the # needed is < 0, delete pending_matches and reset it from scratch? Or maybe just start printing entire pending_matches object to log to try and figure out why this happened?

Like before it was immediately after he SPRT failure on a network.

Need 27 match games. Requested 29, deleted 0. Oldest 15.68m ago. Will schedule selfplay.

XXX uploaded match f93cd4982d2bba8a7fb76760be9901d4fc607a111a558f97aff53e7677ec9b62
SPRT: Early fail pop: {"network1":"8824583931dc0f3413d25705a4e72d422f80ad4ee3638868ad39d3b332652982","network2":"ed26f634a3420ced1cef437f4cddd7e35edafcf793b96d4cbaf2e7da376ccfec","network1_losses":33,"network1_wins":12,"game_count":45,"number_to_play":400,"options":{"resignation_percent":"10","randomcnt":"0","noise":"false","visits":"3200","playouts":"0"},"options_hash":"8e437d","_id":"5aadd214ebeda60e2c0497f8","requests":[{"timestamp":1521345929048,"seed":"3622623671912139643"},{"timestamp":1521345932954,"seed":"3226139990829136811"},{"timestamp":1521345938787,"seed":"2557155410038009750"},{"timestamp":1521345965922,"seed":"3925623932857379858"},{"timestamp":1521345971981,"seed":"17458578028137527491"},{"timestamp":1521345974010,"seed":"5992318922943291896"},{"timestamp":1521345976948,"seed":"12811115790200819308"},{"timestamp":1521345979071,"seed":"7488966503405055592"},{"timestamp":1521345988481,"seed":"13122158322265282672"},{"timestamp":1521346005988,"seed":"10770396349175175485"},{"timestamp":1521346007490,"seed":"864387796117271014"},{"timestamp":1521346016945,"seed":"5356990381087401261"},{"timestamp":1521346018485,"seed":"6787760858301177244"},{"timestamp":1521346031914,"seed":"1322313171513927563"},{"timestamp":1521346040727,"seed":"7088643837857073078"},{"timestamp":1521346042580,"seed":"5983102895078507977"},{"timestamp":1521346047588,"seed":"17279154290498930662"},{"timestamp":1521346172813,"seed":"8647660177999678318"},{"timestamp":1521346188580,"seed":"9029631774768582047"},{"timestamp":1521346310889,"seed":"5798060580576638875"},{"timestamp":1521346315225,"seed":"14487095303315980572"},{"timestamp":1521346562299,"seed":"760580179687574154"},{"timestamp":1521346637937,"seed":"2529658144412196046"},{"timestamp":1521346754649,"seed":"2971691535435856706"},{"timestamp":1521346763545,"seed":"2979022599416202336"},{"timestamp":1521346803948,"seed":"1260081741144071505"},{"timestamp":1521346804295,"seed":"6824963067569484723"},{"timestamp":1521346806184,"seed":"1084040722763230593"}],"game_color":true}
XXX uploaded match 4bc50a02d8d994d1791703d0ba58b3448ab2f2db4522b9e5256801e1fbfc70eb
Need -13 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.

So it seems if we fail a network and remote it from the pending_matches list, and a match arrives for that deleted game, that is how things get corrupted. I don't know why though.

**Comment by roy7** [comment]
In case it'll help, I've added a dump of the whole pending_matches list to the log file after any SPRT fail pop is done.

**Comment by Dorus** [comment]
Something does not properly reset on a match update, but then it goes correct most of the time.

> wins":12,"game_count":45,"number_to_play":400

I'm missing loses, but 400-12 doesn't indicate it should stop yet. Possibly it's the "game_count":45, that didn't reset right? It would be nice if we could reproduce this bug or spot it in action....

**Comment by roy7** [comment]
Happened again tonight. We have more logging now though...

**Comment by roy7** [comment]
Has to do with matches getting too old I guess.

Need 6 match games. Requested 10, deleted 0. Oldest 29.26m ago. Will schedule selfplay.
XXX  uploaded match 38b3d07dbd75244ecb9edae141a766451f04c5819dbf1b3a783102f7a5135646
Cleared match cache.
Need 5 match games. Requested 9, deleted 0. Oldest 29.47m ago. Will schedule selfplay.
Need 5 match games. Requested 9, deleted 0. Oldest 29.55m ago. Will schedule selfplay.
Need 5 match games. Requested 9, deleted 0. Oldest 29.56m ago. Will schedule selfplay.
Need 5 match games. Requested 9, deleted 0. Oldest 29.65m ago. Will schedule selfplay.
XXX uploaded match f50fbe06e13c41696534a1c7974b0780e601327f79c9657caba58ef5cce24b48
Cleared match cache.
Need 4 match games. Requested 9, deleted 0. Oldest 29.80m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
XXX uploaded match 82079fd41f3f67c8a1f47def4e426e6ea217e27fc1e79fef7a2d3192c115960b
Cleared match cache.
Need 3 match games. Requested 7, deleted 1. Oldest 30.01m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need 3 match games. Requested 7, deleted 0. Oldest 28.49m ago. Will schedule selfplay.
XXX  uploaded match 4c122e46bfec5f5cf89f8ef8ffda6f2671e1342a30b69251bc344f9ef9dccf66
Cleared match cache.
Need 2 match games. Requested 6, deleted 0. Oldest 28.56m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need 2 match games. Requested 6, deleted 0. Oldest 28.77m ago. Will schedule selfplay.
Need 2 match games. Requested 6, deleted 0. Oldest 28.89m ago. Will schedule selfplay.
Need 2 match games. Requested 6, deleted 0. Oldest 28.90m ago. Will schedule selfplay.
Need 2 match games. Requested 6, deleted 0. Oldest 29.02m ago. Will schedule selfplay.
Need 2 match games. Requested 6, deleted 0. Oldest 29.84m ago. Will schedule selfplay.
Need 2 match games. Requested 6, deleted 0. Oldest 29.95m ago. Will schedule selfplay.
Need 2 match games. Requested 5, deleted 1. Oldest 30.31m ago. Will schedule selfplay.
Need 2 match games. Requested 5, deleted 0. Oldest 29.89m ago. Will schedule selfplay.
XXX  uploaded match 828aee6b5eb7dcc73ff7bf317b5b0a1c7ae93a21f4318268e97f38f2c3a69f6b
Cleared match cache.
Need 1 match games. Requested 5, deleted 0. Oldest 29.90m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need 1 match games. Requested 3, deleted 2. Oldest 30.37m ago. Will schedule selfplay.
Need 1 match games. Requested 3, deleted 0. Oldest 29.33m ago. Will schedule selfplay.
Need 1 match games. Requested 3, deleted 0. Oldest 29.54m ago. Will schedule selfplay.
Need 1 match games. Requested 3, deleted 0. Oldest 29.63m ago. Will schedule selfplay.
XXX uploaded match 437ad639a7c2665db713401a58ba031abfbaf36b39a5fd4ccc039b58db9916a9
Cleared match cache.
Need 0 match games. Requested 3, deleted 0. Oldest 29.82m ago. Will schedule selfplay.
Need 0 match games. Requested 3, deleted 0. Oldest 29.85m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need 0 match games. Requested 2, deleted 1. Oldest 30.19m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.56m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.63m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.65m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.66m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.71m ago. Will schedule selfplay.
Need 0 match games. Requested 2, deleted 0. Oldest 29.89m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 1. Oldest 30.13m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 27.95m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.05m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.08m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.21m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.31m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.48m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.61m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 28.89m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.25m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.41m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.41m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.55m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.63m ago. Will schedule selfplay.
Need 0 match games. Requested 1, deleted 0. Oldest 29.82m ago. Will schedule selfplay.
Need 0 match games. Requested 0, deleted 1. Oldest 30.10m ago. Will schedule selfplay.
Need 0 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need 0 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
XXX  uploaded match 9d8f0899a6006821ed5570f2243b3931c7970642d1d2f7868f6c8b0c7b41e3a4
Cleared match cache.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -1 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
XXX uploaded match b4ee4dd2a11ca9da7c5c5f904f213e3401d07ab8039bdc4a73d75bf9c169e8d8
Cleared match cache.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -2 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.

As really old/slow matches arrive it keeps going lower and lower.

Need -14 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -14 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
XXX uploaded match 44823bd9dc47db5d0669c32391a7a42ea0a8e4e7fc03ff16def62ea87bd70378
Cleared match cache.
Need -15 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
Cleared match table cache.
Need -15 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -15 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.
Need -15 match games. Requested 0, deleted 0. Oldest 0.00m ago. Will schedule selfplay.

**Comment by roy7** [comment]
Ok when the new network we uploaded never got started, here was the pending_matches.

Pending is now: ```
[{"network1":"417efd19f6f3e287eadeb416b007b75a7ef8cd796b0e4591b1aa95a33f4f4a2c","network2":null,"network1_losses":0,"network1_wins":0,"game_count":0,"number_to_play":400,"is_test":false,"options":{"resignatio
n_percent":"5","randomcnt":"0","noise":"false","visits":"3200"},"options_hash":"0ebb2f","_id":"5afe2e04ea1463439f8546ca","requests":[]},{"network1":"a39b64cced7224e29565ef9b0745eabd3a501571a58249d4a790d4fdb0b01af8","network2
":"d821463056b7527e9c4969641834e3ee6f7cf874fc0a27f3f95172a301c4cff3","network1_losses":187,"network1_wins":253,"game_count":440,"number_to_play":400,"is_test":false,"options":{"resignation_percent":"5","randomcnt":"0","noise
":"false","visits":"3200","playouts":"0"},"options_hash":"0ebb2f","_id":"5afddd21ea1463439f8546c9","requests":[],"game_color":true}]
```

**Comment by roy7** [comment]
Hopefully solved by https://github.com/gcp/leela-zero-server/commit/fcb5f8bba3b30c1c08daf2589feefed2ce5e5098.

I left logging in there so it'll log and unshift every time until match hits 400 games. Eventually we should clean that up. Perhaps instead of removing the >1 check we should have checked for >1 and number_to_play < game_count.

**Comment by roy7** [comment]
Haven't seen this in a month so I will close assuming it is fixed for good.
