### ISSUE TITLE
License inconsistency between README.md and package.json

### ISSUE THREAD

**Issue by gslin** [gcp/leela-zero-server#4]
In `README.md`:

> The code is released under the AGPLv3 or later.

In `package.json`:

>  "license": "ISC",

**Comment by roy7** [comment]
Thanks, I'll fix that. First time making a github project from scratch and I didn't even realize a license appeared in package.json!

**Comment by roy7** [comment]
Done. https://github.com/gcp/leela-zero-server/commit/c787a0d5dfccb8fd652908ab9e04a018de2db220
