### ISSUE TITLE
Add network sizes blocks x filters to "networks"

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero-server#46]
I believe you should be able to update the tables just by ids.

largest TBD network id | training_count | hash | blocks | filters
-- | -- | -- | -- | --
1 | 9000 | e6779c9b | 1 | 8
4 | 107000 | 857b975e | 4 | 32
57 | 2669812 | c83e1b6e | 5 | 64
91 | 4710167 | b3b00c6d | 6 | 128
111 | 6182848 | e9c2c70b | 10 | 128

If it were SQL:
```sql
UPDATE networks
SET blocks = 4, filters = 32
WHERE training_count > 9000 AND training_count <= 107000
```

**Comment by roy7** [comment]
Network #s are generated on the fly, they were just added due to popular demand. There's no network # or ELO scores in the database itself. So it isn't quite this simple. :)

If someone wanted they could make a little stand alone script to run one and read every network file and update the database with the needed info.

**Comment by Mardak** [comment]
Oh, then just do it by training_count. Updated the table in the initial comment.

**Comment by Mardak** [comment]
Also noticed that in the historical messages, it says "moved to 5 blocks x 64 filters" while the architecture column shows [filters]x[blocks]. Not sure if it's desired to standardize on one way…

**Comment by rchs819** [comment]
I did a stand-alone script to scan past networks last night, I’ll do final checking and submit a PR soon

**Comment by rchs819** [comment]
@Mardak 
> Also noticed that in the historical messages, it says "moved to 5 blocks x 64 filters" while the architecture column shows [filters]x[blocks]. Not sure if it's desired to standardize on one way…

Agree we need to standardize the network architecture, I see people use one or the other interchangeably, any ideas on which one to choose?

**Comment by roy7** [comment]
We used to use 5x64 in the old days. I'll change things to the new style.
