### ISSUE TITLE
not in gzip format

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero-server#67]
After I started my own server, and then run `./autogtp`, it says the following error on the client side:

```
AutoGTP v15
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...

gzip: networks/3f6c8dd85e888bec8b0bcc3006c33954e4be5df8a24660b03fcf3e128fd54338.gz: not in gzip format
Net filename: networks/3f6c8dd85e888bec8b0bcc3006c33954e4be5df8a24660b03fcf3e128fd54338
Network connection to server failed.
NetworkException: Failed to fetch the network
Retrying in 30 s.
```

On client side, all `zero.sjeng.org` have already been changed to `127.0.0.1:8080` to point to my server. I noticed that README said there should be a dummy `auth_key` file on server side. I created this file with empty content. Is it correct? And I don't know what's the meaning of this file. It can't find anything of putting auth_key in the http request in the client-side code.

**Comment by roy7** [comment]
auth_key is used in submit-network to prevent others from uploading networks. Make it any text string you want (say 1234) and then if you use submit-network you also use "key=1234".

Be sure networks/3f6c8dd85e888bec8b0bcc3006c33954e4be5df8a24660b03fcf3e128fd54338.gz actually is a gzip file? And copy it to networks/best-network.gz

**Comment by zhanzhenzhen** [comment]
@roy7 As far as I understand it, there should be another auth_key file in the autogtp side? But I can't find anything about it.

But it seems the error isn't about the key. I already used this command on the server:
```
curl -o network/best-network.gz http://zero.sjeng.org/best-network
```

Why it isn't in gz format?

```
$ ls -al network
total 39008
drwxrwxr-x 2 ubuntu ubuntu     4096 Apr 23 11:50 .
drwxrwxr-x 9 ubuntu ubuntu     4096 Apr 23 12:56 ..
-rw-rw-r-- 1 ubuntu ubuntu 39932885 Apr 23 12:48 best-network.gz
```

**Comment by zhanzhenzhen** [comment]
@roy7 FYI, this is the server output:
```
$ node server.js
best_network_hash_promise begins
	rss        48.68 MB
	heapTotal  31.91 MB
	heapUsed   16.26 MB
	external   17.36 MB
Streams prepared
	rss        49.05 MB
	heapTotal  31.91 MB
	heapUsed   16.31 MB
	external   17.39 MB
0 networks.
undefined games.
listening on 8080
Streams completed: 3f6c8dd85e888bec8b0bcc3006c33954e4be5df8a24660b03fcf3e128fd54338
	rss        95.02 MB
	heapTotal  31.33 MB
	heapUsed   12.57 MB
	external   62.68 MB
Current best hash 3f6c8dd85e888bec8b0bcc3006c33954e4be5df8a24660b03fcf3e128fd54338
::ffff:116.192.6.194 Sending index.html
fetching data for elograph.json, should be called once per day or when `cachematches` is cleared
::ffff:127.0.0.1 (undefined)  got task: selfplay
```

**Comment by zhanzhenzhen** [comment]
My auth_key on the server is currently 0 byte.

**Comment by rchs819** [comment]
Here is little discrepancy between local server (`localhost:8080`) and live server (`zero.sjeng.org`)

On live server, the `/networks` (with `s`) folder is actually served by `nginx`, not `node` (@roy7 Please correct if I'm wrong)

So if you wanna achieve the same setting on `localhost`, try adding the following line to serve the network files using `node`

```
app.use('/static', express.static('static', { maxage: '365d', etag: true }));

// Sever network files using `node` (Please note the `s`)
app.use('/networks', express.static('network'));

```
