### ISSUE TITLE
Allow non-promoting matches to be queued against the best network

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero-server#7]
Sometimes we want to run non-promotion matches, for excample to test the HBest network or different shaped networks (like the 6x128 one) without promoting it. However against the current best network, that currently means it gets auto-promoted.

**Comment by rchs819** [comment]
@roy7 / @gcp 

The normal match is always `challenger` vs `best`, and `challenger` gets promoted if win rate >= 55%

Just wondering, if we want to do a non-promoting matches with `test` network against `best` network
Could we reverse the order by queuing `best` vs `test` match? 

Will this work?

**Comment by roy7** [comment]
I think the plan is to support a testonly flag with submit-match, and add tests so the promotions only happen if !testonly. I've not added that but you could feel free. :)
