### ISSUE TITLE
Strange behaviour in best-network.gz headers since last promote.

### ISSUE THREAD

**Issue by ssj-gz** [gcp/leela-zero-server#72]
Hi,

cfb2ce28 was promoted approx half an hour ago, and I'm seeing some strange output when checking the headers of zero.sjeng.org/networks/best-network.gz with curl:

```
[simon@simon-laptop][10:45:49]
[~/tmp/DONTSYNC/windows-qemu]>curl -I zero.sjeng.org/networks/best-network.gz
HTTP/1.1 200 OK
Server: nginx/1.13.12
Date: Sun, 29 Apr 2018 09:45:50 GMT
Content-Type: application/octet-stream
Content-Length: 39966151
Last-Modified: Sun, 29 Apr 2018 09:45:02 GMT
Connection: keep-alive
ETag: "5ae5941e-261d5c7"
Accept-Ranges: bytes

[simon@simon-laptop][10:45:50]
[~/tmp/DONTSYNC/windows-qemu]>curl -I zero.sjeng.org/networks/best-network.gz
HTTP/1.1 200 OK
Server: nginx/1.13.12
Date: Sun, 29 Apr 2018 09:45:51 GMT
Content-Type: application/octet-stream
Content-Length: 39966151
Last-Modified: Sun, 29 Apr 2018 09:45:02 GMT
Connection: keep-alive
ETag: "5ae5941e-261d5c7"
Accept-Ranges: bytes

[simon@simon-laptop][10:45:51]
[~/tmp/DONTSYNC/windows-qemu]>curl -I zero.sjeng.org/networks/best-network.gz
HTTP/1.1 200 OK
Server: nginx/1.13.12
Date: Sun, 29 Apr 2018 09:46:40 GMT
Content-Type: application/octet-stream
Content-Length: 39944857
Last-Modified: Sun, 29 Apr 2018 09:46:33 GMT
Connection: keep-alive
ETag: "5ae59479-2618299"
Accept-Ranges: bytes

[simon@simon-laptop][10:47:17]
[~/tmp/DONTSYNC/windows-qemu]>curl -I zero.sjeng.org/networks/best-network.gz
HTTP/1.1 200 OK
Server: nginx/1.13.12
Date: Sun, 29 Apr 2018 09:51:13 GMT
Content-Type: application/octet-stream
Content-Length: 39966151
Last-Modified: Sun, 29 Apr 2018 09:49:27 GMT
Connection: keep-alive
ETag: "5ae59527-261d5c7"
Accept-Ranges: bytes

```

It's like best-network.gz is continuously overwritten and, more disturbingly, the Content-Length seems to alternate between 39944857 and 39966151.  

I'm guessing it's not causing any problems as cfb2ce28 games seem to be being uploaded OK, but it's definitely odd new behaviour :) 

**Edit**: the two Content-Lengths correspond to cfb2 and the previous best, 1586, so if autogtp uses the best-network.gz (I don't know if it does) this might actually cause problems :/

**Comment by roy7** [comment]
The error in the re-write is that it's checking of the best network was the loser, and if so, it's promoting the winner. This is wrong. It should only promote the winner if the lower was the best network and was also network2. If the best network is network1 that means it won it's match vs the prior best network, it shouldn't promote back to the old network in that case.

**Comment by roy7** [comment]
Hopefully fixed it here. https://github.com/gcp/leela-zero-server/commit/7d41f3908d3504ce0d9d36011efeb16dff609704

**Comment by rchs819** [comment]
Sorry, I wasn't available to look into the issue. Thanks @roy7 

It would be great if we could have unit-test PR merged, so that we unit test against autogtp related routes like `/get-task`, `/submit` and `/submit-match`

**Comment by roy7** [comment]
Yes sorry I'll knock that out @rchs819.
