### ISSUE TITLE
why all test and passed network are marked with color to green?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero-server#76]
it was blue

**Comment by l1t1** [comment]
it is same as ???'s color and made confuse.
suggest use another color

**Comment by Mardak** [comment]
Can you post a screenshot? I'm guessing it might be some caching in your browser. What if you hold the Shift key and click on reload?

This is what I see right now:
![screen shot 2018-05-01 at 5 09 36 pm](https://user-images.githubusercontent.com/438537/39499417-a956b420-4d62-11e8-8fc2-f8e98a55d54d.png)

**Comment by rchs819** [comment]
it is the JavaScript caching issue
It shows green on my screen, and shows grey after `Ctrl + F5` refresh.

**Comment by l1t1** [comment]
![canvas52](https://user-images.githubusercontent.com/23301704/39500554-eb73c566-4de7-11e8-9aa6-fdbe69f9abd9.png)
firefox 56 64bit windows
