### ISSUE TITLE
Problems with the graph

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero-server#78]
I use 3 different machines (2 different Internet providers) to access http://zero.sjeng.org/
with different browsers
Several weeks ago I could not see graph on one, then after some enhancement on two,
then with the last was gone with the latest changes.

Good news - I can see it with a specific browser that is not my default or preferred one.
And the new graph is excellent.

It is not a big problem for me, as I can live without the graph :) or use yandex browser with
home page at zero.sjeng.org

But I think that a growing segment of visitors, might never see the graph,
what would cripple the promotion of LZ.

**Comment by Marcin1960** [comment]
I one of the browsers that fails is Pale Moon

**Comment by roy7** [comment]
Still having any problems? I'm not sure how to figure out what's wrong.

**Comment by Mardak** [comment]
Looks like different browsers have different behaviors for iframes. Sometimes adding the ?1 works…

**Comment by roy7** [comment]
I guess we could try merging the html into the server page directly and not use the iframe.

**Comment by jkiliani** [comment]
The (actually very nice) improved graph with the new scaling and new symbol for test matches doesn't work for me anymore. Was better before this change, can we somehow give users an option which page to view?

**Comment by rchs819** [comment]
@jkiliani which browser are you using?
