### ISSUE TITLE
now the best network list table is ordered by hash?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero-server#86]
Times are in GMT+0100 (CET)					
Best Network Hash					
#	Upload Date	Hash	Architecture	Games	Training #
131	2018/1/8 20:19	ffc1e51b	64x5	148665	2002537
130	2017/12/11 18:59	fe7a6c28	64x5	20389	955000
129	2017/11/17 8:09	fe3f6afd	32x4	44001	19000
128	2018/1/7 5:14	fca07541	64x5	62034	1883473
127	2018/3/6 18:53	fc2b9ac3	128x10	62153	4873768

**Comment by l1t1** [comment]
![2018-05-05_085229 png](https://user-images.githubusercontent.com/23301704/39658151-aaf0c84e-4fff-11e8-9501-c87a84ab4fca.jpg)
picture is more clear

**Comment by roy7** [comment]
We had lots of thing to fix after the ELF network was added internally for some selfplay games. I think networks table and graph all look correct now?

**Comment by l1t1** [comment]
thanks
