### ISSUE TITLE
Match network name sanity check

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero-server#9]
When a match is queued, check that the network being queued is in network/. If not, ignore the request to add match and throw an error back. This will prevent typos from putting illegal networks into the match queue.

**Comment by rchs819** [comment]
@roy7 

https://github.com/gcp/leela-zero-server/blob/e1c5755b473dbcbd48450edf6ca5db33208488ff/server.js#L444-L445

Just wondering, what type of match is it when `network2` is null?
Is it self-play?

**Comment by roy7** [comment]
@rchs819 network2==null means the opponent will be assigned when the match starts, vs the current best network. This way you could line up 10 matches and if an early one promotes, the later ones will face the new best network not the original one.

**Comment by rchs819** [comment]
Cool, thanks
