### ISSUE TITLE
No ELF self-play for `task/0`

### ISSUE THREAD

**Issue by bood** [gcp/leela-zero-server#94]
Tried several times of `curl http://zero.sjeng.org/get-task/0`
No ELF self-play is returned.

```
> curl http://zero.sjeng.org/get-task/0
{"cmd":"selfplay","hash":"ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199","required_client_version":"15","random_seed":"8641093934871031854","leelaz_version":"0.13","options_hash":"7aaaeb","options":{"playouts":"0","visits":"3201","resignation_percent":"0","noise":"true","randomcnt":"999"}}
```

I wish I can use this to avoid match,  I don't want to waste time downloading networks frequently since my network is slow.

**Comment by Mardak** [comment]
We can't send ELF games to `task/0` right now as any old client can be requesting it. Only new clients can handle the new network format.
